### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fcastrovilli** [fcastrovilli/00185fm-v3#2]
- [ ] feat: filter system with `tags` and `dates`
- [ ] feat: `schedule` collection
- [ ] feat: include `time` logic to `playlists` collection
- [ ] feat: infinite scroll `search` results
